from django.urls import path

from association.views import *
from product.views import *
from users.views import *
from work.views import *

urlpatterns = [
    path('', index, name='index'),
    path('contact_us/', contact_us, name='contact_us'),
    path('shop_page/', read_four_products, name='shop_page'),
    path('about/', about_show, name='about'),
    path('formation/', formation_show, name='formation'),
    path('one_project/<int:id>/', read_one_projects, name='one_project'),
    path('temoignage/', read_four_temoignage, name='temoignage'),
    path('project_page/', read_four_projects, name='project_page'),
    path('read_one_shop/<int:id>/', read_one_products, name='read_one_shop'),
    path('delete_shop/<int:id>/', deleteProduct, name='delete_shop'),
    path('save_contact_us/', save_contact_us, name='save_contact_us'),
    path('delete_contact_us/<int:id>/', delete_contact_us, name='delete_contact_us'),
    path('answering/<int:id>/', send_answer_contact_us, name='send_answer_contact_us'),
    path('login/', login_panel, name='login'),
    path('connexion/', login, name='connexion'),
    path('registration/', registration, name='register'),
    path('save/', register, name='save'),
    path('confirmation/', confirmation_panel, name='confirmation'),
    path('mail_confirmation/', mail_confirmation, name='mail_confirmation'),
    path('reset_password/', reset_password, name='reset_password'),
    path('verify_email/', verify_email, name='verify_email'),
    path('unlock_account/', mail_found, name='unlock_account'),
    path('update_password/<int:id>/', update_password, name='update_password'),
    path('resend_confirmation/<str:email>/', resend_confirmation, name='resend_confirmation'),
    path('verification/', verification_email, name='verification'),
    path('dashboard/', dashboard_redirect, name='dashboard'),
    path('save-selections/', user_counts_by_month, name='save_selections'),
    path('admin_profile/', admin_profile, name='admin_profile'),
    path('calendar_admin/', calendar_admin, name='calendar_admin'),
    path('add_event/', save_data, name='add_event'),
    path('admin_message/', admin_message, name="admin_message"),
    path('update_profile/', admin_update_profile, name='update_profile'),
    path('update_image/', update_image, name='update_image'),
    # path('<str:room>/', room, name="room"),
    path('check/<int:id>/', checkview, name='check'),
    path('getMessages/<str:room>/', getMessages, name="getMessages"),
    path('send', send, name="send"),
    path('contact_list', contacts_list, name="contact_list"),
    path('list_of_technicien/', technicien_list, name="list_of_technicien"),
    path('list_user/', users_list, name="list_user"),
    path('add_user', addMember, name='add_user'),
    path('add_technicien', addTechnicien, name='add_technicien'),
    path('technicien_show/<int:id>/', technicien_show, name='technicien_show'),
    path('update_technicien/<int:id>/', update_technicien, name='update_technicien'),
    path('delete_user/<int:id>/', delete_technicien, name='delete_user'),
    path('association_manager/', list_of_associations, name='association_manager'),
    path('one_association/<int:id>/', read_one_association, name='read_one_association'),
    path('create_association/', create_associations, name='create_association'),
    path('create_product/', createProduct, name='create_product'),
    path('list_product/', read_all_products, name='list_product'),
    path('create_formation/', createFormation, name='createFormation'),
    path('read_all_formation/', read_all_formations, name='readAllFormation'),
    path('read_one_formation/<int:id>/', read_one_formation, name='read_one_formation'),
    path('delete_formation/<int:id>/', deleteFormation, name='delete_formation'),
    path('problem/', problem, name='problem'),
    path('work/', work, name='work'),
    path('create_work/', createWork, name='create_work'),
    path('show_one_work/<int:id>/', editWork, name='show_one_work'),
    path('update_work/', updateWork, name='update_work'),
    path('delete_work/<int:id>/', deleteWork, name='delete_work'),
    path('read_temoignage/', read_all_temoignage, name='read_temoignage'),
    path('create_temoignage/', createTemoignage, name='create_temoignage'),
    path('read_all_project/', read_all_projects, name='read_all_projects'),
    path('accept_proj/<int:id>/', accept_project, name='accept_project'),
    path('create_project/', createProject, name='create_project'),
    path('read_all_activities/', read_all_activities, name='read_all_activities'),
    path('delete_activity<int:id>/', delete_activity, name='delete_activity'),
    path('create_activity/', create_activity, name='create_activity'),
    path('create_member_association/', create_member_associations, name='create_member_association'),
    path('delete_temoignage/<int:id>/', delete_temoignage, name='delete_temoignage'),
    path('commander/', commander_products, name='commander'),
    path('show_story/', show_story, name='show_story'),
    path('get_event', calendar_view, name='get_event'),
    path('logout/', logout, name='logout'),
]
